### ISSUE TITLE
"No HAT detected" on 2018-04-18-raspbian-stretch

### ISSUE THREAD

**Issue by claremacrae** [claremacrae/raspi_hat_data#1]
I've tried this with multiple HATs and two different Raspberry Pi 3s, and in each case, `copy_hat_data.sh` reports `No HAT detected`.

I've used the RasPiO Pro Hat successfully, on this OS, and yet there is no `/proc/device-tree/hat/` directory found.

So it looks like somehow since, since I first write this script, the way of detecting HAT config has changed.

**Comment by shawaj** [comment]
Wonder if it would be worth adding the new way, once found, to here - https://github.com/raspberrypi/hats/blob/master/README.md

**Comment by claremacrae** [comment]
Have asked a question about this in the Raspberry Pi forums:
https://www.raspberrypi.org/forums/viewtopic.php?f=100&t=213787

**Comment by claremacrae** [comment]
The script still works with the Sense HAT! 

It doesn't work with RasPiO Pro HAT, on two different Pi 3s.

Looks like I need a bigger data sample.

**Comment by shawaj** [comment]
Yeah I guess it has to have an eeprom with a valid data blob on it to show there

**Comment by claremacrae** [comment]
Turns out that the device I was using is not a HAT - and with real HATs, such as the Sense HAT, the script still works fine on Raspian Stretch.
